# Generated by Django 5.0.1 on 2024-01-19 15:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlosPost',
            new_name='BlogPost',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='last_update',
            new_name='last_updated',
        ),
    ]
